import Ambassador from '../../assets/icons/ambassador.inline.svg';
import Arrow from '../../assets/icons/arrow.inline.svg';
import Barchart from '../../assets/icons/barchart.inline.svg';
import Bug from '../../assets/icons/bug.inline.svg';
import Calendar from '../../assets/icons/calendar.inline.svg';
import Camera from '../../assets/icons/camera.inline.svg';
import ChatBubble from '../../assets/icons/chatbubble.inline.svg';
import Change from '../../assets/icons/change.inline.svg';
import ChatSquare from '../../assets/icons/chat-square.inline.svg';
import ChevronDown from '../../assets/icons/chevronDown.inline.svg';
import ChevronRightFilled from '../../assets/icons/chevron.right.filled.inline.svg';
import Cicd from '../../assets/icons/icon-cicd.inline.svg';
import CICD from '../../assets/icons/CICD.inline.svg';
import Cloud from '../../assets/icons/icon-cloud.inline.svg';
import CloudNative from '../../assets/icons/cloud-native.inline.svg';
import Code from '../../assets/icons/code.inline.svg';
import Collaboration from '../../assets/icons/collaboration.inline.svg';
import Container from '../../assets/icons/container.inline.svg';
import Customization from '../../assets/icons/customization.inline.svg';
import Diagnose from '../../assets/icons/icon-diagnose.inline.svg';
import Document from '../../assets/icons/document.inline.svg';
import Documents from '../../assets/icons/documents.inline.svg';
import DocumentIcon from '../../assets/icons/icon-document.inline.svg';
import EdgeStackIcon from '../../assets/icons/edge-stack-icon.inline.svg';
import Environment from '../../assets/icons/environment.inline.svg';
import FAQs from '../../assets/icons/faqs.inline.svg';
import Github from '../../assets/icons/github.inline.svg';
import GitPlusk8s from '../../assets/icons/gitplusk8s.inline.svg';
import HighFive from '../../assets/icons/highFive.inline.svg';
import HighFiveNoShadow from '../../assets/icons/high-five-no-shadow.inline.svg';
import Information from '../../assets/icons/information.inline.svg';
import Kubernetes from '../../assets/icons/kubernetes.inline.svg';
import K8s from '../../assets/icons/K8s.inline.svg';
import Layers from '../../assets/icons/layers.inline.svg';
import LearnIcon from '../../assets/icons/icon-learn.inline.svg';
import LinkIcon from '../../assets/icons/link.inline.svg';
import Log from '../../assets/icons/log.inline.svg';
import LoopIcon from '../../assets/icons/loop-icon.inline.svg';
import MailIcon from '../../assets/icons/mail-icon.inline.svg';
import Number1 from '../../assets/icons/number1.inline.svg';
import Number2 from '../../assets/icons/number2.inline.svg';
import Number3 from '../../assets/icons/number3.inline.svg';
import Number4 from '../../assets/icons/number4.inline.svg';
import NumberFour from '../../assets/icons/numberFour.inline.svg';
import NumberOne from '../../assets/icons/numberOne.inline.svg';
import NumberThree from '../../assets/icons/numberThree.inline.svg';
import NumberTwo from '../../assets/icons/numberTwo.inline.svg';
import Outline from '../../assets/icons/outline.inline.svg';
import PlayVideo from '../../assets/icons/playVideo.inline.svg';
import PlusIcon from '../../assets/icons/plus-icon.inline.svg';
import PlusIconOpen from '../../assets/icons/plus-icon-open.inline.svg';
import Points from '../../assets/icons/points.inline.svg';
import Pyramid from '../../assets/images/pyramid.inline.svg';
import Reload from '../../assets/icons/reload.inline.svg';
import RemoteTesting from '../../assets/icons/remote-testing.inline.svg';
import Replay from '../../assets/icons/replay.inline.svg';
import RightArrow from '../../assets/images/right-arrow.inline.svg';
import Rocket from '../../assets/icons/rocket.inline.svg';
import Rollouts from '../../assets/icons/icon-rollouts.inline.svg';
import Search from '../../assets/icons/search.inline.svg';
import Security from '../../assets/icons/security.inline.svg';
import Service from '../../assets/icons/service.inline.svg';
import ServiceCatalog from '../../assets/icons/icon-service_catalog.inline.svg';
import ServiceCatalogPurple from '../../assets/icons/service-catalog-purple.inline.svg';
import Settings from '../../assets/icons/settings.inline.svg';
import ShareKnow from '../../assets/images/share-know.inline.svg';
import ShareSee from '../../assets/images/share-see.inline.svg';
import ShipIcon from '../../assets/icons/ship.icon.inline.svg';
import SlackIcon from '../../assets/icons/slack-icon.inline.svg';
import Speedometer from '../../assets/icons/speedometer.inline.svg';
import Spinner from '../../assets/icons/spinner.inline.svg';
import SystemVisualization from '../../assets/icons/system-visualization.inline.svg';
import Tada from '../../assets/icons/tada.inline.svg';
import TelepresenceIcon from '../../assets/icons/telepresence-icon.inline.svg';
import TelepresenceOrangeIcon from '../../assets/icons/telepresence-orange-icon.inline.svg';
import TerminalShadow from '../../assets/icons/terminal-shadow.inline.svg';
import TerminalTraditional from '../../assets/icons/terminal-traditional.inline.svg';
import Timer from '../../assets/icons/timer.inline.svg';
import Tool from '../../assets/icons/tool.inline.svg';
import Tools from '../../assets/icons/tools.inline.svg';
import ToolsGreen from '../../assets/icons/icon-tools.inline.svg';
import Upload from '../../assets/icons/upload.inline.svg';
import VersionIcon from '../../assets/icons/versionIcon.inline.svg';

const icons = new Map();
icons.set('ambassador', Ambassador);
icons.set('arrow', Arrow);
icons.set('barchart', Barchart);
icons.set('bug', Bug);
icons.set('calendar', Calendar);
icons.set('camera', Camera);
icons.set('chat-bubble', ChatBubble);
icons.set('change', Change);
icons.set('chat-square', ChatSquare);
icons.set('chevron-down', ChevronDown);
icons.set('chevron-right-filled', ChevronRightFilled);
icons.set('cicd', Cicd);
icons.set('CICD', CICD);
icons.set('cloud', Cloud);
icons.set('cloud-native', CloudNative);
icons.set('code', Code);
icons.set('collaboration', Collaboration);
icons.set('container', Container);
icons.set('customization', Customization);
icons.set('diagnose', Diagnose);
icons.set('document', Document);
icons.set('documents', Documents);
icons.set('document-icon', DocumentIcon);
icons.set('edge-stack-icon', EdgeStackIcon);
icons.set('environment', Environment);
icons.set('faqs', FAQs);
icons.set('github', Github);
icons.set('gitplusk8s', GitPlusk8s);
icons.set('high-five', HighFive);
icons.set('kubernetes', Kubernetes);
icons.set('k8s', K8s);
icons.set('layers', Layers);
icons.set('high-five-no-shadow', HighFiveNoShadow);
icons.set('information', Information);
icons.set('learn-icon', LearnIcon);
icons.set('link-icon', LinkIcon);
icons.set('log', Log);
icons.set('loop-icon', LoopIcon);
icons.set('mail-icon', MailIcon);
icons.set('number-1', Number1);
icons.set('number-2', Number2);
icons.set('number-3', Number3);
icons.set('number-4', Number4);
icons.set('number-four', NumberFour);
icons.set('number-one', NumberOne);
icons.set('number-three', NumberThree);
icons.set('number-two', NumberTwo);
icons.set('outline', Outline);
icons.set('play-video', PlayVideo);
icons.set('plus-icon-open', PlusIconOpen);
icons.set('plus-icon', PlusIcon);
icons.set('points', Points);
icons.set('pyramid', Pyramid);
icons.set('reload', Reload);
icons.set('remote-testing', RemoteTesting);
icons.set('replay', Replay);
icons.set('right-arrow', RightArrow);
icons.set('rocket', Rocket);
icons.set('rollouts', Rollouts);
icons.set('search', Search);
icons.set('security', Security);
icons.set('service', Service);
icons.set('service-catalog', ServiceCatalog);
icons.set('service-catalog-purple', ServiceCatalogPurple);
icons.set('settings', Settings);
icons.set('share-know', ShareKnow);
icons.set('share-see', ShareSee);
icons.set('ship-icon', ShipIcon);
icons.set('slack-icon', SlackIcon);
icons.set('speedometer', Speedometer);
icons.set('spinner', Spinner);
icons.set('system-visualization', SystemVisualization);
icons.set('tada', Tada);
icons.set('telepresence-icon', TelepresenceIcon);
icons.set('telepresence-orange-icon', TelepresenceOrangeIcon);
icons.set('terminal-shadow', TerminalShadow);
icons.set('terminal-traditional', TerminalTraditional);
icons.set('timer', Timer);
icons.set('tool', Tool);
icons.set('tools', Tools);
icons.set('tools-green', ToolsGreen);
icons.set('upload', Upload);
icons.set('version-icon', VersionIcon);

export default icons;
