name: "Broken Link Checker"
on: [push]
jobs:
  "Check":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
        with:
          path: site
      - uses: actions/checkout@v4
        with:
          repository: datawire/getambassador.io-blc2
          path: blc
      - run: yarn
        working-directory: site
      - run: yarn build
        working-directory: site
      - run: npm install
        working-directory: blc
      - name: Run checker
        run: |
          set -o pipefail
          (TARGET=../site PRODUCT=telepresenceio make -C . > blc.log) || ! (grep 'has a broken' blc.log)
        working-directory: blc
      - uses: actions/upload-artifact@v4
        with:
          name: blc.log
          path: blc/blc.log
        if: always()
