name: "Quality Assurance"
on: [push]
jobs:
  "Lint":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: yarn
      - name: "yarn build"
        run: |
          yarn build
      - name: "Dirty check"
        run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            PAGER= git diff --cached
            exit 1
          fi
      - name: yarn run eslint .
        run: |
          yarn run eslint . |& tee lint.log
          ! grep problem lint.log
